# Scaffolding generated by Casein v5.2.0.0

module Casein
  class DishesController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Dishes'
      @dishes = Dish.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View dish'
      @dish = Dish.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new dish'
      @dish = Dish.new
    end

    def create
      @dish = Dish.new dish_params

      if @dish.save
        flash[:notice] = 'Dish created'
        redirect_to casein_dishes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new dish'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update dish'

      @dish = Dish.find params[:id]

      if @dish.update_attributes dish_params
        flash[:notice] = 'Dish has been updated'
        redirect_to casein_dishes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this dish'
        render action: :show
      end
    end

    def destroy
      @dish = Dish.find params[:id]

      @dish.destroy
      flash[:notice] = 'Dish has been deleted'
      redirect_to casein_dishes_path
    end

    private

    def dish_params
      params.require(:dish).permit(:name, :description)
    end
  end
end
