# Scaffolding generated by Casein v5.2.0.0

module Casein
  class RestaurantsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Restaurants'
      @restaurants = Restaurant.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View restaurant'
      @restaurant = Restaurant.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new restaurant'
      @restaurant = Restaurant.new
    end

    def create
      @restaurant = Restaurant.new restaurant_params

      if @restaurant.save
        flash[:notice] = 'Restaurant created'
        redirect_to casein_restaurants_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new restaurant'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update restaurant'

      @restaurant = Restaurant.find params[:id]

      if @restaurant.update_attributes restaurant_params
        flash[:notice] = 'Restaurant has been updated'
        redirect_to casein_restaurants_path
      else
        flash.now[:warning] = 'There were problems when trying to update this restaurant'
        render action: :show
      end
    end

    def destroy
      @restaurant = Restaurant.find params[:id]

      @restaurant.destroy
      flash[:notice] = 'Restaurant has been deleted'
      redirect_to casein_restaurants_path
    end

    private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number)
    end
  end
end
